"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _weather_summary_Temp from './weather-summary-Temp.bones.json'
import _weather_summary_Hum from './weather-summary-Hum.bones.json'
import _weather_summary_Vel from './weather-summary-Vel.bones.json'
import _weather_summary_Dir from './weather-summary-Dir.bones.json'
import _weather_summary_Precip from './weather-summary-Precip.bones.json'
import _weather_summary_Rad from './weather-summary-Rad.bones.json'

configureBoneyard({"color":"#dff3ec","animate":"shimmer","shimmerColor":"#f8fcf9","speed":"1.2s"})

registerBones({
  "weather-summary-Temp": _weather_summary_Temp,
  "weather-summary-Hum": _weather_summary_Hum,
  "weather-summary-Vel": _weather_summary_Vel,
  "weather-summary-Dir": _weather_summary_Dir,
  "weather-summary-Precip": _weather_summary_Precip,
  "weather-summary-Rad": _weather_summary_Rad,
})
